spring:
  cloud:
    nacos:
      discovery:
        server-addr: nacos
  datasource:
    #JDBC drivers
    driver-class-name: com.mysql.cj.jdbc.Driver
    #database url
    url: jdbc:mysql://mysql:3306/product?serverTimezone=Asia/Shanghai
    #database username and password
    username: demouser
    password: 123456
    #database connection pool
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 100
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*

      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 100
      validation-query: select 1
  data:
    redis:
      repositories:
        #forbid redis to scan repositories
        enabled: false
      host: redis
      database: 0
      password: 123456
    #MongoDB configuration
    mongodb:
      host: mongo1
      port: 27017
      database: oomall
      username: demouser
      password: '123456'
      authentication-database: oomall
  jackson:
    time-zone: GMT+8
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
rocketmq:
  name-server: rocketmq-namesrv:9876
  producer:
    group: goods-producer
#  consumer:
#    group: goods-consumer

server:
  port: 8081
  tomcat:
    threads:
      max: 200
      min-spare: 100
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

oomall:
  core:
    page-size:
      max: 1000
      default: 10
  product:
    timeout: 3600
  activity:
    timeout: 3600
  category:
    timeout: 3600
  onsale:
    timeout: 3600
  data-center: 1

