package cn.edu.xmu.oomall.wechatpay.mapper.generator;

import cn.edu.xmu.oomall.wechatpay.mapper.generator.po.RefundTransPo;
import cn.edu.xmu.oomall.wechatpay.mapper.generator.po.RefundTransPoExample.Criteria;
import cn.edu.xmu.oomall.wechatpay.mapper.generator.po.RefundTransPoExample.Criterion;
import cn.edu.xmu.oomall.wechatpay.mapper.generator.po.RefundTransPoExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class RefundTransPoSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public String insertSelective(RefundTransPo row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("wechatpay_refund_trans");
        
        if (row.getId() != null) {
            sql.VALUES("`id`", "#{id,jdbcType=BIGINT}");
        }
        
        if (row.getSubMchid() != null) {
            sql.VALUES("`sub_mchid`", "#{subMchid,jdbcType=VARCHAR}");
        }
        
        if (row.getTransactionId() != null) {
            sql.VALUES("`transaction_id`", "#{transactionId,jdbcType=VARCHAR}");
        }
        
        if (row.getAmountTotal() != null) {
            sql.VALUES("`amount_total`", "#{amountTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountPayerTotal() != null) {
            sql.VALUES("`amount_payer_total`", "#{amountPayerTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountSettlementTotal() != null) {
            sql.VALUES("`amount_settlement_total`", "#{amountSettlementTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountRefund() != null) {
            sql.VALUES("`amount_refund`", "#{amountRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountPayerRefund() != null) {
            sql.VALUES("`amount_payer_refund`", "#{amountPayerRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountSettlementRefund() != null) {
            sql.VALUES("`amount_settlement_refund`", "#{amountSettlementRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountDiscountRefund() != null) {
            sql.VALUES("`amount_discount_refund`", "#{amountDiscountRefund,jdbcType=INTEGER}");
        }
        
        if (row.getOutRefundNo() != null) {
            sql.VALUES("`out_refund_no`", "#{outRefundNo,jdbcType=VARCHAR}");
        }
        
        if (row.getOutTradeNo() != null) {
            sql.VALUES("`out_trade_no`", "#{outTradeNo,jdbcType=VARCHAR}");
        }
        
        if (row.getUserReceivedAccount() != null) {
            sql.VALUES("`user_received_account`", "#{userReceivedAccount,jdbcType=VARCHAR}");
        }
        
        if (row.getCreateTime() != null) {
            sql.VALUES("`create_time`", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (row.getStatus() != null) {
            sql.VALUES("`status`", "#{status,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public String selectByExample(RefundTransPoExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("`id`");
        } else {
            sql.SELECT("`id`");
        }
        sql.SELECT("`sub_mchid`");
        sql.SELECT("`transaction_id`");
        sql.SELECT("`amount_total`");
        sql.SELECT("`amount_payer_total`");
        sql.SELECT("`amount_settlement_total`");
        sql.SELECT("`amount_refund`");
        sql.SELECT("`amount_payer_refund`");
        sql.SELECT("`amount_settlement_refund`");
        sql.SELECT("`amount_discount_refund`");
        sql.SELECT("`out_refund_no`");
        sql.SELECT("`refund_id`");
        sql.SELECT("`out_trade_no`");
        sql.SELECT("`user_received_account`");
        sql.SELECT("`create_time`");
        sql.SELECT("`status`");
        sql.FROM("wechatpay_refund_trans");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        RefundTransPo row = (RefundTransPo) parameter.get("row");
        RefundTransPoExample example = (RefundTransPoExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("wechatpay_refund_trans");
        
        if (row.getId() != null) {
            sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        }
        
        if (row.getSubMchid() != null) {
            sql.SET("`sub_mchid` = #{row.subMchid,jdbcType=VARCHAR}");
        }
        
        if (row.getTransactionId() != null) {
            sql.SET("`transaction_id` = #{row.transactionId,jdbcType=VARCHAR}");
        }
        
        if (row.getAmountTotal() != null) {
            sql.SET("`amount_total` = #{row.amountTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountPayerTotal() != null) {
            sql.SET("`amount_payer_total` = #{row.amountPayerTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountSettlementTotal() != null) {
            sql.SET("`amount_settlement_total` = #{row.amountSettlementTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountRefund() != null) {
            sql.SET("`amount_refund` = #{row.amountRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountPayerRefund() != null) {
            sql.SET("`amount_payer_refund` = #{row.amountPayerRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountSettlementRefund() != null) {
            sql.SET("`amount_settlement_refund` = #{row.amountSettlementRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountDiscountRefund() != null) {
            sql.SET("`amount_discount_refund` = #{row.amountDiscountRefund,jdbcType=INTEGER}");
        }
        
        if (row.getOutRefundNo() != null) {
            sql.SET("`out_refund_no` = #{row.outRefundNo,jdbcType=VARCHAR}");
        }
        
        if (row.getRefundId() != null) {
            sql.SET("`refund_id` = #{row.refundId,jdbcType=VARCHAR}");
        }
        
        if (row.getOutTradeNo() != null) {
            sql.SET("`out_trade_no` = #{row.outTradeNo,jdbcType=VARCHAR}");
        }
        
        if (row.getUserReceivedAccount() != null) {
            sql.SET("`user_received_account` = #{row.userReceivedAccount,jdbcType=VARCHAR}");
        }
        
        if (row.getCreateTime() != null) {
            sql.SET("`create_time` = #{row.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{row.status,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("wechatpay_refund_trans");
        
        sql.SET("`id` = #{row.id,jdbcType=BIGINT}");
        sql.SET("`sub_mchid` = #{row.subMchid,jdbcType=VARCHAR}");
        sql.SET("`transaction_id` = #{row.transactionId,jdbcType=VARCHAR}");
        sql.SET("`amount_total` = #{row.amountTotal,jdbcType=INTEGER}");
        sql.SET("`amount_payer_total` = #{row.amountPayerTotal,jdbcType=INTEGER}");
        sql.SET("`amount_settlement_total` = #{row.amountSettlementTotal,jdbcType=INTEGER}");
        sql.SET("`amount_refund` = #{row.amountRefund,jdbcType=INTEGER}");
        sql.SET("`amount_payer_refund` = #{row.amountPayerRefund,jdbcType=INTEGER}");
        sql.SET("`amount_settlement_refund` = #{row.amountSettlementRefund,jdbcType=INTEGER}");
        sql.SET("`amount_discount_refund` = #{row.amountDiscountRefund,jdbcType=INTEGER}");
        sql.SET("`out_refund_no` = #{row.outRefundNo,jdbcType=VARCHAR}");
        sql.SET("`refund_id` = #{row.refundId,jdbcType=VARCHAR}");
        sql.SET("`out_trade_no` = #{row.outTradeNo,jdbcType=VARCHAR}");
        sql.SET("`user_received_account` = #{row.userReceivedAccount,jdbcType=VARCHAR}");
        sql.SET("`create_time` = #{row.createTime,jdbcType=TIMESTAMP}");
        sql.SET("`status` = #{row.status,jdbcType=VARCHAR}");
        
        RefundTransPoExample example = (RefundTransPoExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public String updateByPrimaryKeySelective(RefundTransPo row) {
        SQL sql = new SQL();
        sql.UPDATE("wechatpay_refund_trans");
        
        if (row.getSubMchid() != null) {
            sql.SET("`sub_mchid` = #{subMchid,jdbcType=VARCHAR}");
        }
        
        if (row.getTransactionId() != null) {
            sql.SET("`transaction_id` = #{transactionId,jdbcType=VARCHAR}");
        }
        
        if (row.getAmountTotal() != null) {
            sql.SET("`amount_total` = #{amountTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountPayerTotal() != null) {
            sql.SET("`amount_payer_total` = #{amountPayerTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountSettlementTotal() != null) {
            sql.SET("`amount_settlement_total` = #{amountSettlementTotal,jdbcType=INTEGER}");
        }
        
        if (row.getAmountRefund() != null) {
            sql.SET("`amount_refund` = #{amountRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountPayerRefund() != null) {
            sql.SET("`amount_payer_refund` = #{amountPayerRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountSettlementRefund() != null) {
            sql.SET("`amount_settlement_refund` = #{amountSettlementRefund,jdbcType=INTEGER}");
        }
        
        if (row.getAmountDiscountRefund() != null) {
            sql.SET("`amount_discount_refund` = #{amountDiscountRefund,jdbcType=INTEGER}");
        }
        
        if (row.getOutRefundNo() != null) {
            sql.SET("`out_refund_no` = #{outRefundNo,jdbcType=VARCHAR}");
        }
        
        if (row.getRefundId() != null) {
            sql.SET("`refund_id` = #{refundId,jdbcType=VARCHAR}");
        }
        
        if (row.getOutTradeNo() != null) {
            sql.SET("`out_trade_no` = #{outTradeNo,jdbcType=VARCHAR}");
        }
        
        if (row.getUserReceivedAccount() != null) {
            sql.SET("`user_received_account` = #{userReceivedAccount,jdbcType=VARCHAR}");
        }
        
        if (row.getCreateTime() != null) {
            sql.SET("`create_time` = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("`status` = #{status,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("`id` = #{id,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    protected void applyWhere(SQL sql, RefundTransPoExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}