package cn.edu.xmu.oomall.wechatpay.mapper.generator.po;

import cn.edu.xmu.javaee.core.aop.CopyFrom;
import cn.edu.xmu.oomall.wechatpay.dao.bo.DivPayTrans;

import java.time.LocalDateTime;

@CopyFrom({DivPayTrans.class})
public class DivPayTransPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.appid
     *
     * @mbg.generated
     */
    private String appid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.sub_mchid
     *
     * @mbg.generated
     */
    private String subMchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.out_order_no
     *
     * @mbg.generated
     */
    private String outOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.order_id
     *
     * @mbg.generated
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.state
     *
     * @mbg.generated
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_div_pay_trans.success_time
     *
     * @mbg.generated
     */
    private LocalDateTime successTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.id
     *
     * @return the value of wechatpay_div_pay_trans.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.id
     *
     * @param id the value for wechatpay_div_pay_trans.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.appid
     *
     * @return the value of wechatpay_div_pay_trans.appid
     *
     * @mbg.generated
     */
    public String getAppid() {
        return appid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.appid
     *
     * @param appid the value for wechatpay_div_pay_trans.appid
     *
     * @mbg.generated
     */
    public void setAppid(String appid) {
        this.appid = appid == null ? null : appid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.sub_mchid
     *
     * @return the value of wechatpay_div_pay_trans.sub_mchid
     *
     * @mbg.generated
     */
    public String getSubMchid() {
        return subMchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.sub_mchid
     *
     * @param subMchid the value for wechatpay_div_pay_trans.sub_mchid
     *
     * @mbg.generated
     */
    public void setSubMchid(String subMchid) {
        this.subMchid = subMchid == null ? null : subMchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.transaction_id
     *
     * @return the value of wechatpay_div_pay_trans.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.transaction_id
     *
     * @param transactionId the value for wechatpay_div_pay_trans.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.out_order_no
     *
     * @return the value of wechatpay_div_pay_trans.out_order_no
     *
     * @mbg.generated
     */
    public String getOutOrderNo() {
        return outOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.out_order_no
     *
     * @param outOrderNo the value for wechatpay_div_pay_trans.out_order_no
     *
     * @mbg.generated
     */
    public void setOutOrderNo(String outOrderNo) {
        this.outOrderNo = outOrderNo == null ? null : outOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.order_id
     *
     * @return the value of wechatpay_div_pay_trans.order_id
     *
     * @mbg.generated
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.order_id
     *
     * @param orderId the value for wechatpay_div_pay_trans.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.state
     *
     * @return the value of wechatpay_div_pay_trans.state
     *
     * @mbg.generated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.state
     *
     * @param state the value for wechatpay_div_pay_trans.state
     *
     * @mbg.generated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_div_pay_trans.success_time
     *
     * @return the value of wechatpay_div_pay_trans.success_time
     *
     * @mbg.generated
     */
    public LocalDateTime getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_div_pay_trans.success_time
     *
     * @param successTime the value for wechatpay_div_pay_trans.success_time
     *
     * @mbg.generated
     */
    public void setSuccessTime(LocalDateTime successTime) {
        this.successTime = successTime;
    }
}