package cn.edu.xmu.oomall.wechatpay.mapper.generator.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class PayTransPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public PayTransPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSpAppidIsNull() {
            addCriterion("`sp_appid` is null");
            return (Criteria) this;
        }

        public Criteria andSpAppidIsNotNull() {
            addCriterion("`sp_appid` is not null");
            return (Criteria) this;
        }

        public Criteria andSpAppidEqualTo(String value) {
            addCriterion("`sp_appid` =", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidNotEqualTo(String value) {
            addCriterion("`sp_appid` <>", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidGreaterThan(String value) {
            addCriterion("`sp_appid` >", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidGreaterThanOrEqualTo(String value) {
            addCriterion("`sp_appid` >=", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidLessThan(String value) {
            addCriterion("`sp_appid` <", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidLessThanOrEqualTo(String value) {
            addCriterion("`sp_appid` <=", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidLike(String value) {
            addCriterion("`sp_appid` like", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidNotLike(String value) {
            addCriterion("`sp_appid` not like", value, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidIn(List<String> values) {
            addCriterion("`sp_appid` in", values, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidNotIn(List<String> values) {
            addCriterion("`sp_appid` not in", values, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidBetween(String value1, String value2) {
            addCriterion("`sp_appid` between", value1, value2, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpAppidNotBetween(String value1, String value2) {
            addCriterion("`sp_appid` not between", value1, value2, "spAppid");
            return (Criteria) this;
        }

        public Criteria andSpMchidIsNull() {
            addCriterion("`sp_mchid` is null");
            return (Criteria) this;
        }

        public Criteria andSpMchidIsNotNull() {
            addCriterion("`sp_mchid` is not null");
            return (Criteria) this;
        }

        public Criteria andSpMchidEqualTo(String value) {
            addCriterion("`sp_mchid` =", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidNotEqualTo(String value) {
            addCriterion("`sp_mchid` <>", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidGreaterThan(String value) {
            addCriterion("`sp_mchid` >", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidGreaterThanOrEqualTo(String value) {
            addCriterion("`sp_mchid` >=", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidLessThan(String value) {
            addCriterion("`sp_mchid` <", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidLessThanOrEqualTo(String value) {
            addCriterion("`sp_mchid` <=", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidLike(String value) {
            addCriterion("`sp_mchid` like", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidNotLike(String value) {
            addCriterion("`sp_mchid` not like", value, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidIn(List<String> values) {
            addCriterion("`sp_mchid` in", values, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidNotIn(List<String> values) {
            addCriterion("`sp_mchid` not in", values, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidBetween(String value1, String value2) {
            addCriterion("`sp_mchid` between", value1, value2, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSpMchidNotBetween(String value1, String value2) {
            addCriterion("`sp_mchid` not between", value1, value2, "spMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidIsNull() {
            addCriterion("`sub_mchid` is null");
            return (Criteria) this;
        }

        public Criteria andSubMchidIsNotNull() {
            addCriterion("`sub_mchid` is not null");
            return (Criteria) this;
        }

        public Criteria andSubMchidEqualTo(String value) {
            addCriterion("`sub_mchid` =", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotEqualTo(String value) {
            addCriterion("`sub_mchid` <>", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidGreaterThan(String value) {
            addCriterion("`sub_mchid` >", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidGreaterThanOrEqualTo(String value) {
            addCriterion("`sub_mchid` >=", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidLessThan(String value) {
            addCriterion("`sub_mchid` <", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidLessThanOrEqualTo(String value) {
            addCriterion("`sub_mchid` <=", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidLike(String value) {
            addCriterion("`sub_mchid` like", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotLike(String value) {
            addCriterion("`sub_mchid` not like", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidIn(List<String> values) {
            addCriterion("`sub_mchid` in", values, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotIn(List<String> values) {
            addCriterion("`sub_mchid` not in", values, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidBetween(String value1, String value2) {
            addCriterion("`sub_mchid` between", value1, value2, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotBetween(String value1, String value2) {
            addCriterion("`sub_mchid` not between", value1, value2, "subMchid");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("`description` is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("`description` is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("`description` =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("`description` <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("`description` >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("`description` >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("`description` <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("`description` <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("`description` like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("`description` not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("`description` in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("`description` not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("`description` between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("`description` not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("`out_trade_no` is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("`out_trade_no` is not null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("`out_trade_no` =", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("`out_trade_no` <>", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("`out_trade_no` >", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("`out_trade_no` >=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("`out_trade_no` <", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("`out_trade_no` <=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLike(String value) {
            addCriterion("`out_trade_no` like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("`out_trade_no` not like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("`out_trade_no` in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("`out_trade_no` not in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("`out_trade_no` between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("`out_trade_no` not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andTimeExpireIsNull() {
            addCriterion("`time_expire` is null");
            return (Criteria) this;
        }

        public Criteria andTimeExpireIsNotNull() {
            addCriterion("`time_expire` is not null");
            return (Criteria) this;
        }

        public Criteria andTimeExpireEqualTo(LocalDateTime value) {
            addCriterion("`time_expire` =", value, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireNotEqualTo(LocalDateTime value) {
            addCriterion("`time_expire` <>", value, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireGreaterThan(LocalDateTime value) {
            addCriterion("`time_expire` >", value, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`time_expire` >=", value, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireLessThan(LocalDateTime value) {
            addCriterion("`time_expire` <", value, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`time_expire` <=", value, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireIn(List<LocalDateTime> values) {
            addCriterion("`time_expire` in", values, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireNotIn(List<LocalDateTime> values) {
            addCriterion("`time_expire` not in", values, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`time_expire` between", value1, value2, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andTimeExpireNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`time_expire` not between", value1, value2, "timeExpire");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidIsNull() {
            addCriterion("`payer_sp_openid` is null");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidIsNotNull() {
            addCriterion("`payer_sp_openid` is not null");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidEqualTo(String value) {
            addCriterion("`payer_sp_openid` =", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidNotEqualTo(String value) {
            addCriterion("`payer_sp_openid` <>", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidGreaterThan(String value) {
            addCriterion("`payer_sp_openid` >", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidGreaterThanOrEqualTo(String value) {
            addCriterion("`payer_sp_openid` >=", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidLessThan(String value) {
            addCriterion("`payer_sp_openid` <", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidLessThanOrEqualTo(String value) {
            addCriterion("`payer_sp_openid` <=", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidLike(String value) {
            addCriterion("`payer_sp_openid` like", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidNotLike(String value) {
            addCriterion("`payer_sp_openid` not like", value, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidIn(List<String> values) {
            addCriterion("`payer_sp_openid` in", values, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidNotIn(List<String> values) {
            addCriterion("`payer_sp_openid` not in", values, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidBetween(String value1, String value2) {
            addCriterion("`payer_sp_openid` between", value1, value2, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andPayerSpOpenidNotBetween(String value1, String value2) {
            addCriterion("`payer_sp_openid` not between", value1, value2, "payerSpOpenid");
            return (Criteria) this;
        }

        public Criteria andAmountTotalIsNull() {
            addCriterion("`amount_total` is null");
            return (Criteria) this;
        }

        public Criteria andAmountTotalIsNotNull() {
            addCriterion("`amount_total` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountTotalEqualTo(Integer value) {
            addCriterion("`amount_total` =", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalNotEqualTo(Integer value) {
            addCriterion("`amount_total` <>", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalGreaterThan(Integer value) {
            addCriterion("`amount_total` >", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_total` >=", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalLessThan(Integer value) {
            addCriterion("`amount_total` <", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_total` <=", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalIn(List<Integer> values) {
            addCriterion("`amount_total` in", values, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalNotIn(List<Integer> values) {
            addCriterion("`amount_total` not in", values, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalBetween(Integer value1, Integer value2) {
            addCriterion("`amount_total` between", value1, value2, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_total` not between", value1, value2, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("`transaction_id` is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("`transaction_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(String value) {
            addCriterion("`transaction_id` =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(String value) {
            addCriterion("`transaction_id` <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(String value) {
            addCriterion("`transaction_id` >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("`transaction_id` >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(String value) {
            addCriterion("`transaction_id` <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("`transaction_id` <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLike(String value) {
            addCriterion("`transaction_id` like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotLike(String value) {
            addCriterion("`transaction_id` not like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<String> values) {
            addCriterion("`transaction_id` in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<String> values) {
            addCriterion("`transaction_id` not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(String value1, String value2) {
            addCriterion("`transaction_id` between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(String value1, String value2) {
            addCriterion("`transaction_id` not between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTradeStateIsNull() {
            addCriterion("`trade_state` is null");
            return (Criteria) this;
        }

        public Criteria andTradeStateIsNotNull() {
            addCriterion("`trade_state` is not null");
            return (Criteria) this;
        }

        public Criteria andTradeStateEqualTo(String value) {
            addCriterion("`trade_state` =", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateNotEqualTo(String value) {
            addCriterion("`trade_state` <>", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateGreaterThan(String value) {
            addCriterion("`trade_state` >", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateGreaterThanOrEqualTo(String value) {
            addCriterion("`trade_state` >=", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateLessThan(String value) {
            addCriterion("`trade_state` <", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateLessThanOrEqualTo(String value) {
            addCriterion("`trade_state` <=", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateLike(String value) {
            addCriterion("`trade_state` like", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateNotLike(String value) {
            addCriterion("`trade_state` not like", value, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateIn(List<String> values) {
            addCriterion("`trade_state` in", values, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateNotIn(List<String> values) {
            addCriterion("`trade_state` not in", values, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateBetween(String value1, String value2) {
            addCriterion("`trade_state` between", value1, value2, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateNotBetween(String value1, String value2) {
            addCriterion("`trade_state` not between", value1, value2, "tradeState");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescIsNull() {
            addCriterion("`trade_state_desc` is null");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescIsNotNull() {
            addCriterion("`trade_state_desc` is not null");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescEqualTo(String value) {
            addCriterion("`trade_state_desc` =", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescNotEqualTo(String value) {
            addCriterion("`trade_state_desc` <>", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescGreaterThan(String value) {
            addCriterion("`trade_state_desc` >", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescGreaterThanOrEqualTo(String value) {
            addCriterion("`trade_state_desc` >=", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescLessThan(String value) {
            addCriterion("`trade_state_desc` <", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescLessThanOrEqualTo(String value) {
            addCriterion("`trade_state_desc` <=", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescLike(String value) {
            addCriterion("`trade_state_desc` like", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescNotLike(String value) {
            addCriterion("`trade_state_desc` not like", value, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescIn(List<String> values) {
            addCriterion("`trade_state_desc` in", values, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescNotIn(List<String> values) {
            addCriterion("`trade_state_desc` not in", values, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescBetween(String value1, String value2) {
            addCriterion("`trade_state_desc` between", value1, value2, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andTradeStateDescNotBetween(String value1, String value2) {
            addCriterion("`trade_state_desc` not between", value1, value2, "tradeStateDesc");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIsNull() {
            addCriterion("`success_time` is null");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIsNotNull() {
            addCriterion("`success_time` is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeEqualTo(LocalDateTime value) {
            addCriterion("`success_time` =", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`success_time` <>", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeGreaterThan(LocalDateTime value) {
            addCriterion("`success_time` >", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`success_time` >=", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeLessThan(LocalDateTime value) {
            addCriterion("`success_time` <", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`success_time` <=", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIn(List<LocalDateTime> values) {
            addCriterion("`success_time` in", values, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`success_time` not in", values, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`success_time` between", value1, value2, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`success_time` not between", value1, value2, "successTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechatpay_pay_trans
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}