package cn.edu.xmu.oomall.wechatpay.mapper.generator.po;

import cn.edu.xmu.javaee.core.aop.CopyFrom;
import cn.edu.xmu.oomall.wechatpay.dao.bo.RefundTrans;

import java.time.LocalDateTime;

@CopyFrom({RefundTrans.class})

public class RefundTransPo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.sub_mchid
     *
     * @mbg.generated
     */
    private String subMchid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.transaction_id
     *
     * @mbg.generated
     */
    private String transactionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.amount_total
     *
     * @mbg.generated
     */
    private Integer amountTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.amount_payer_total
     *
     * @mbg.generated
     */
    private Integer amountPayerTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.amount_settlement_total
     *
     * @mbg.generated
     */
    private Integer amountSettlementTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.amount_refund
     *
     * @mbg.generated
     */
    private Integer amountRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.amount_payer_refund
     *
     * @mbg.generated
     */
    private Integer amountPayerRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.amount_settlement_refund
     *
     * @mbg.generated
     */
    private Integer amountSettlementRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.amount_discount_refund
     *
     * @mbg.generated
     */
    private Integer amountDiscountRefund;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.out_refund_no
     *
     * @mbg.generated
     */
    private String outRefundNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.refund_id
     *
     * @mbg.generated
     */
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.out_trade_no
     *
     * @mbg.generated
     */
    private String outTradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.user_received_account
     *
     * @mbg.generated
     */
    private String userReceivedAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.create_time
     *
     * @mbg.generated
     */
    private LocalDateTime createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechatpay_refund_trans.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.id
     *
     * @return the value of wechatpay_refund_trans.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.id
     *
     * @param id the value for wechatpay_refund_trans.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.sub_mchid
     *
     * @return the value of wechatpay_refund_trans.sub_mchid
     *
     * @mbg.generated
     */
    public String getSubMchid() {
        return subMchid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.sub_mchid
     *
     * @param subMchid the value for wechatpay_refund_trans.sub_mchid
     *
     * @mbg.generated
     */
    public void setSubMchid(String subMchid) {
        this.subMchid = subMchid == null ? null : subMchid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.transaction_id
     *
     * @return the value of wechatpay_refund_trans.transaction_id
     *
     * @mbg.generated
     */
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.transaction_id
     *
     * @param transactionId the value for wechatpay_refund_trans.transaction_id
     *
     * @mbg.generated
     */
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId == null ? null : transactionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.amount_total
     *
     * @return the value of wechatpay_refund_trans.amount_total
     *
     * @mbg.generated
     */
    public Integer getAmountTotal() {
        return amountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.amount_total
     *
     * @param amountTotal the value for wechatpay_refund_trans.amount_total
     *
     * @mbg.generated
     */
    public void setAmountTotal(Integer amountTotal) {
        this.amountTotal = amountTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.amount_payer_total
     *
     * @return the value of wechatpay_refund_trans.amount_payer_total
     *
     * @mbg.generated
     */
    public Integer getAmountPayerTotal() {
        return amountPayerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.amount_payer_total
     *
     * @param amountPayerTotal the value for wechatpay_refund_trans.amount_payer_total
     *
     * @mbg.generated
     */
    public void setAmountPayerTotal(Integer amountPayerTotal) {
        this.amountPayerTotal = amountPayerTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.amount_settlement_total
     *
     * @return the value of wechatpay_refund_trans.amount_settlement_total
     *
     * @mbg.generated
     */
    public Integer getAmountSettlementTotal() {
        return amountSettlementTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.amount_settlement_total
     *
     * @param amountSettlementTotal the value for wechatpay_refund_trans.amount_settlement_total
     *
     * @mbg.generated
     */
    public void setAmountSettlementTotal(Integer amountSettlementTotal) {
        this.amountSettlementTotal = amountSettlementTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.amount_refund
     *
     * @return the value of wechatpay_refund_trans.amount_refund
     *
     * @mbg.generated
     */
    public Integer getAmountRefund() {
        return amountRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.amount_refund
     *
     * @param amountRefund the value for wechatpay_refund_trans.amount_refund
     *
     * @mbg.generated
     */
    public void setAmountRefund(Integer amountRefund) {
        this.amountRefund = amountRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.amount_payer_refund
     *
     * @return the value of wechatpay_refund_trans.amount_payer_refund
     *
     * @mbg.generated
     */
    public Integer getAmountPayerRefund() {
        return amountPayerRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.amount_payer_refund
     *
     * @param amountPayerRefund the value for wechatpay_refund_trans.amount_payer_refund
     *
     * @mbg.generated
     */
    public void setAmountPayerRefund(Integer amountPayerRefund) {
        this.amountPayerRefund = amountPayerRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.amount_settlement_refund
     *
     * @return the value of wechatpay_refund_trans.amount_settlement_refund
     *
     * @mbg.generated
     */
    public Integer getAmountSettlementRefund() {
        return amountSettlementRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.amount_settlement_refund
     *
     * @param amountSettlementRefund the value for wechatpay_refund_trans.amount_settlement_refund
     *
     * @mbg.generated
     */
    public void setAmountSettlementRefund(Integer amountSettlementRefund) {
        this.amountSettlementRefund = amountSettlementRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.amount_discount_refund
     *
     * @return the value of wechatpay_refund_trans.amount_discount_refund
     *
     * @mbg.generated
     */
    public Integer getAmountDiscountRefund() {
        return amountDiscountRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.amount_discount_refund
     *
     * @param amountDiscountRefund the value for wechatpay_refund_trans.amount_discount_refund
     *
     * @mbg.generated
     */
    public void setAmountDiscountRefund(Integer amountDiscountRefund) {
        this.amountDiscountRefund = amountDiscountRefund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.out_refund_no
     *
     * @return the value of wechatpay_refund_trans.out_refund_no
     *
     * @mbg.generated
     */
    public String getOutRefundNo() {
        return outRefundNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.out_refund_no
     *
     * @param outRefundNo the value for wechatpay_refund_trans.out_refund_no
     *
     * @mbg.generated
     */
    public void setOutRefundNo(String outRefundNo) {
        this.outRefundNo = outRefundNo == null ? null : outRefundNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.refund_id
     *
     * @return the value of wechatpay_refund_trans.refund_id
     *
     * @mbg.generated
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.refund_id
     *
     * @param refundId the value for wechatpay_refund_trans.refund_id
     *
     * @mbg.generated
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId == null ? null : refundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.out_trade_no
     *
     * @return the value of wechatpay_refund_trans.out_trade_no
     *
     * @mbg.generated
     */
    public String getOutTradeNo() {
        return outTradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.out_trade_no
     *
     * @param outTradeNo the value for wechatpay_refund_trans.out_trade_no
     *
     * @mbg.generated
     */
    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo == null ? null : outTradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.user_received_account
     *
     * @return the value of wechatpay_refund_trans.user_received_account
     *
     * @mbg.generated
     */
    public String getUserReceivedAccount() {
        return userReceivedAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.user_received_account
     *
     * @param userReceivedAccount the value for wechatpay_refund_trans.user_received_account
     *
     * @mbg.generated
     */
    public void setUserReceivedAccount(String userReceivedAccount) {
        this.userReceivedAccount = userReceivedAccount == null ? null : userReceivedAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.create_time
     *
     * @return the value of wechatpay_refund_trans.create_time
     *
     * @mbg.generated
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.create_time
     *
     * @param createTime the value for wechatpay_refund_trans.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechatpay_refund_trans.status
     *
     * @return the value of wechatpay_refund_trans.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechatpay_refund_trans.status
     *
     * @param status the value for wechatpay_refund_trans.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}