package cn.edu.xmu.oomall.wechatpay.mapper.generator.po;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class RefundTransPoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public RefundTransPoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("`id` is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("`id` is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("`id` =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("`id` <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("`id` >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("`id` >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("`id` <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("`id` <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("`id` in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("`id` not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("`id` between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("`id` not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSubMchidIsNull() {
            addCriterion("`sub_mchid` is null");
            return (Criteria) this;
        }

        public Criteria andSubMchidIsNotNull() {
            addCriterion("`sub_mchid` is not null");
            return (Criteria) this;
        }

        public Criteria andSubMchidEqualTo(String value) {
            addCriterion("`sub_mchid` =", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotEqualTo(String value) {
            addCriterion("`sub_mchid` <>", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidGreaterThan(String value) {
            addCriterion("`sub_mchid` >", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidGreaterThanOrEqualTo(String value) {
            addCriterion("`sub_mchid` >=", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidLessThan(String value) {
            addCriterion("`sub_mchid` <", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidLessThanOrEqualTo(String value) {
            addCriterion("`sub_mchid` <=", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidLike(String value) {
            addCriterion("`sub_mchid` like", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotLike(String value) {
            addCriterion("`sub_mchid` not like", value, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidIn(List<String> values) {
            addCriterion("`sub_mchid` in", values, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotIn(List<String> values) {
            addCriterion("`sub_mchid` not in", values, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidBetween(String value1, String value2) {
            addCriterion("`sub_mchid` between", value1, value2, "subMchid");
            return (Criteria) this;
        }

        public Criteria andSubMchidNotBetween(String value1, String value2) {
            addCriterion("`sub_mchid` not between", value1, value2, "subMchid");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNull() {
            addCriterion("`transaction_id` is null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIsNotNull() {
            addCriterion("`transaction_id` is not null");
            return (Criteria) this;
        }

        public Criteria andTransactionIdEqualTo(String value) {
            addCriterion("`transaction_id` =", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotEqualTo(String value) {
            addCriterion("`transaction_id` <>", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThan(String value) {
            addCriterion("`transaction_id` >", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdGreaterThanOrEqualTo(String value) {
            addCriterion("`transaction_id` >=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThan(String value) {
            addCriterion("`transaction_id` <", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLessThanOrEqualTo(String value) {
            addCriterion("`transaction_id` <=", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdLike(String value) {
            addCriterion("`transaction_id` like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotLike(String value) {
            addCriterion("`transaction_id` not like", value, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdIn(List<String> values) {
            addCriterion("`transaction_id` in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotIn(List<String> values) {
            addCriterion("`transaction_id` not in", values, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdBetween(String value1, String value2) {
            addCriterion("`transaction_id` between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andTransactionIdNotBetween(String value1, String value2) {
            addCriterion("`transaction_id` not between", value1, value2, "transactionId");
            return (Criteria) this;
        }

        public Criteria andAmountTotalIsNull() {
            addCriterion("`amount_total` is null");
            return (Criteria) this;
        }

        public Criteria andAmountTotalIsNotNull() {
            addCriterion("`amount_total` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountTotalEqualTo(Integer value) {
            addCriterion("`amount_total` =", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalNotEqualTo(Integer value) {
            addCriterion("`amount_total` <>", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalGreaterThan(Integer value) {
            addCriterion("`amount_total` >", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_total` >=", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalLessThan(Integer value) {
            addCriterion("`amount_total` <", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_total` <=", value, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalIn(List<Integer> values) {
            addCriterion("`amount_total` in", values, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalNotIn(List<Integer> values) {
            addCriterion("`amount_total` not in", values, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalBetween(Integer value1, Integer value2) {
            addCriterion("`amount_total` between", value1, value2, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_total` not between", value1, value2, "amountTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalIsNull() {
            addCriterion("`amount_payer_total` is null");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalIsNotNull() {
            addCriterion("`amount_payer_total` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalEqualTo(Integer value) {
            addCriterion("`amount_payer_total` =", value, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalNotEqualTo(Integer value) {
            addCriterion("`amount_payer_total` <>", value, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalGreaterThan(Integer value) {
            addCriterion("`amount_payer_total` >", value, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_payer_total` >=", value, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalLessThan(Integer value) {
            addCriterion("`amount_payer_total` <", value, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_payer_total` <=", value, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalIn(List<Integer> values) {
            addCriterion("`amount_payer_total` in", values, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalNotIn(List<Integer> values) {
            addCriterion("`amount_payer_total` not in", values, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalBetween(Integer value1, Integer value2) {
            addCriterion("`amount_payer_total` between", value1, value2, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountPayerTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_payer_total` not between", value1, value2, "amountPayerTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalIsNull() {
            addCriterion("`amount_settlement_total` is null");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalIsNotNull() {
            addCriterion("`amount_settlement_total` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalEqualTo(Integer value) {
            addCriterion("`amount_settlement_total` =", value, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalNotEqualTo(Integer value) {
            addCriterion("`amount_settlement_total` <>", value, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalGreaterThan(Integer value) {
            addCriterion("`amount_settlement_total` >", value, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_settlement_total` >=", value, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalLessThan(Integer value) {
            addCriterion("`amount_settlement_total` <", value, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_settlement_total` <=", value, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalIn(List<Integer> values) {
            addCriterion("`amount_settlement_total` in", values, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalNotIn(List<Integer> values) {
            addCriterion("`amount_settlement_total` not in", values, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalBetween(Integer value1, Integer value2) {
            addCriterion("`amount_settlement_total` between", value1, value2, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementTotalNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_settlement_total` not between", value1, value2, "amountSettlementTotal");
            return (Criteria) this;
        }

        public Criteria andAmountRefundIsNull() {
            addCriterion("`amount_refund` is null");
            return (Criteria) this;
        }

        public Criteria andAmountRefundIsNotNull() {
            addCriterion("`amount_refund` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountRefundEqualTo(Integer value) {
            addCriterion("`amount_refund` =", value, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundNotEqualTo(Integer value) {
            addCriterion("`amount_refund` <>", value, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundGreaterThan(Integer value) {
            addCriterion("`amount_refund` >", value, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_refund` >=", value, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundLessThan(Integer value) {
            addCriterion("`amount_refund` <", value, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_refund` <=", value, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundIn(List<Integer> values) {
            addCriterion("`amount_refund` in", values, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundNotIn(List<Integer> values) {
            addCriterion("`amount_refund` not in", values, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundBetween(Integer value1, Integer value2) {
            addCriterion("`amount_refund` between", value1, value2, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_refund` not between", value1, value2, "amountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundIsNull() {
            addCriterion("`amount_payer_refund` is null");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundIsNotNull() {
            addCriterion("`amount_payer_refund` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundEqualTo(Integer value) {
            addCriterion("`amount_payer_refund` =", value, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundNotEqualTo(Integer value) {
            addCriterion("`amount_payer_refund` <>", value, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundGreaterThan(Integer value) {
            addCriterion("`amount_payer_refund` >", value, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_payer_refund` >=", value, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundLessThan(Integer value) {
            addCriterion("`amount_payer_refund` <", value, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_payer_refund` <=", value, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundIn(List<Integer> values) {
            addCriterion("`amount_payer_refund` in", values, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundNotIn(List<Integer> values) {
            addCriterion("`amount_payer_refund` not in", values, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundBetween(Integer value1, Integer value2) {
            addCriterion("`amount_payer_refund` between", value1, value2, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountPayerRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_payer_refund` not between", value1, value2, "amountPayerRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundIsNull() {
            addCriterion("`amount_settlement_refund` is null");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundIsNotNull() {
            addCriterion("`amount_settlement_refund` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundEqualTo(Integer value) {
            addCriterion("`amount_settlement_refund` =", value, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundNotEqualTo(Integer value) {
            addCriterion("`amount_settlement_refund` <>", value, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundGreaterThan(Integer value) {
            addCriterion("`amount_settlement_refund` >", value, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_settlement_refund` >=", value, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundLessThan(Integer value) {
            addCriterion("`amount_settlement_refund` <", value, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_settlement_refund` <=", value, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundIn(List<Integer> values) {
            addCriterion("`amount_settlement_refund` in", values, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundNotIn(List<Integer> values) {
            addCriterion("`amount_settlement_refund` not in", values, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundBetween(Integer value1, Integer value2) {
            addCriterion("`amount_settlement_refund` between", value1, value2, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountSettlementRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_settlement_refund` not between", value1, value2, "amountSettlementRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundIsNull() {
            addCriterion("`amount_discount_refund` is null");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundIsNotNull() {
            addCriterion("`amount_discount_refund` is not null");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundEqualTo(Integer value) {
            addCriterion("`amount_discount_refund` =", value, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundNotEqualTo(Integer value) {
            addCriterion("`amount_discount_refund` <>", value, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundGreaterThan(Integer value) {
            addCriterion("`amount_discount_refund` >", value, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundGreaterThanOrEqualTo(Integer value) {
            addCriterion("`amount_discount_refund` >=", value, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundLessThan(Integer value) {
            addCriterion("`amount_discount_refund` <", value, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundLessThanOrEqualTo(Integer value) {
            addCriterion("`amount_discount_refund` <=", value, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundIn(List<Integer> values) {
            addCriterion("`amount_discount_refund` in", values, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundNotIn(List<Integer> values) {
            addCriterion("`amount_discount_refund` not in", values, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundBetween(Integer value1, Integer value2) {
            addCriterion("`amount_discount_refund` between", value1, value2, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andAmountDiscountRefundNotBetween(Integer value1, Integer value2) {
            addCriterion("`amount_discount_refund` not between", value1, value2, "amountDiscountRefund");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoIsNull() {
            addCriterion("`out_refund_no` is null");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoIsNotNull() {
            addCriterion("`out_refund_no` is not null");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoEqualTo(String value) {
            addCriterion("`out_refund_no` =", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotEqualTo(String value) {
            addCriterion("`out_refund_no` <>", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoGreaterThan(String value) {
            addCriterion("`out_refund_no` >", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoGreaterThanOrEqualTo(String value) {
            addCriterion("`out_refund_no` >=", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoLessThan(String value) {
            addCriterion("`out_refund_no` <", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoLessThanOrEqualTo(String value) {
            addCriterion("`out_refund_no` <=", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoLike(String value) {
            addCriterion("`out_refund_no` like", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotLike(String value) {
            addCriterion("`out_refund_no` not like", value, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoIn(List<String> values) {
            addCriterion("`out_refund_no` in", values, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotIn(List<String> values) {
            addCriterion("`out_refund_no` not in", values, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoBetween(String value1, String value2) {
            addCriterion("`out_refund_no` between", value1, value2, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andOutRefundNoNotBetween(String value1, String value2) {
            addCriterion("`out_refund_no` not between", value1, value2, "outRefundNo");
            return (Criteria) this;
        }

        public Criteria andRefundIdIsNull() {
            addCriterion("`refund_id` is null");
            return (Criteria) this;
        }

        public Criteria andRefundIdIsNotNull() {
            addCriterion("`refund_id` is not null");
            return (Criteria) this;
        }

        public Criteria andRefundIdEqualTo(String value) {
            addCriterion("`refund_id` =", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotEqualTo(String value) {
            addCriterion("`refund_id` <>", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdGreaterThan(String value) {
            addCriterion("`refund_id` >", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdGreaterThanOrEqualTo(String value) {
            addCriterion("`refund_id` >=", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdLessThan(String value) {
            addCriterion("`refund_id` <", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdLessThanOrEqualTo(String value) {
            addCriterion("`refund_id` <=", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdLike(String value) {
            addCriterion("`refund_id` like", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotLike(String value) {
            addCriterion("`refund_id` not like", value, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdIn(List<String> values) {
            addCriterion("`refund_id` in", values, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotIn(List<String> values) {
            addCriterion("`refund_id` not in", values, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdBetween(String value1, String value2) {
            addCriterion("`refund_id` between", value1, value2, "refundId");
            return (Criteria) this;
        }

        public Criteria andRefundIdNotBetween(String value1, String value2) {
            addCriterion("`refund_id` not between", value1, value2, "refundId");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNull() {
            addCriterion("`out_trade_no` is null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIsNotNull() {
            addCriterion("`out_trade_no` is not null");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoEqualTo(String value) {
            addCriterion("`out_trade_no` =", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotEqualTo(String value) {
            addCriterion("`out_trade_no` <>", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThan(String value) {
            addCriterion("`out_trade_no` >", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoGreaterThanOrEqualTo(String value) {
            addCriterion("`out_trade_no` >=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThan(String value) {
            addCriterion("`out_trade_no` <", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLessThanOrEqualTo(String value) {
            addCriterion("`out_trade_no` <=", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoLike(String value) {
            addCriterion("`out_trade_no` like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotLike(String value) {
            addCriterion("`out_trade_no` not like", value, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoIn(List<String> values) {
            addCriterion("`out_trade_no` in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotIn(List<String> values) {
            addCriterion("`out_trade_no` not in", values, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoBetween(String value1, String value2) {
            addCriterion("`out_trade_no` between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andOutTradeNoNotBetween(String value1, String value2) {
            addCriterion("`out_trade_no` not between", value1, value2, "outTradeNo");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountIsNull() {
            addCriterion("`user_received_account` is null");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountIsNotNull() {
            addCriterion("`user_received_account` is not null");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountEqualTo(String value) {
            addCriterion("`user_received_account` =", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotEqualTo(String value) {
            addCriterion("`user_received_account` <>", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountGreaterThan(String value) {
            addCriterion("`user_received_account` >", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountGreaterThanOrEqualTo(String value) {
            addCriterion("`user_received_account` >=", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountLessThan(String value) {
            addCriterion("`user_received_account` <", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountLessThanOrEqualTo(String value) {
            addCriterion("`user_received_account` <=", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountLike(String value) {
            addCriterion("`user_received_account` like", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotLike(String value) {
            addCriterion("`user_received_account` not like", value, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountIn(List<String> values) {
            addCriterion("`user_received_account` in", values, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotIn(List<String> values) {
            addCriterion("`user_received_account` not in", values, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountBetween(String value1, String value2) {
            addCriterion("`user_received_account` between", value1, value2, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andUserReceivedAccountNotBetween(String value1, String value2) {
            addCriterion("`user_received_account` not between", value1, value2, "userReceivedAccount");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("`create_time` is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("`create_time` is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("`create_time` =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("`create_time` >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("`create_time` <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("`create_time` <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("`create_time` in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("`create_time` not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("`create_time` not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("`status` is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("`status` is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("`status` =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("`status` <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("`status` >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("`status` >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("`status` <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("`status` <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("`status` like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("`status` not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("`status` in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("`status` not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("`status` between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("`status` not between", value1, value2, "status");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wechatpay_refund_trans
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}